export const AnimationMetaData = {
  smallExplosion: {
    Kind: 'smallExplosion',
    Image: Object.assign(new Image(), { src: '/effect/smallExplosion.png' }),
    AnimationFrame: 4,
    width: 32,
    height: 32,
    scalingFactor: 1,
  },
  mediumYellowExplosion: {
    Kind: 'mediumYellowExplosion',
    Image: Object.assign(new Image(), { src: '/effect/mediumYellowExplosion.png' }),
    AnimationFrame: 9,
    width: 63.5,
    height: 63.5,
    scalingFactor: 0.9,
  },
  mediumGreenExplosion: {
    Kind: 'mediumGreenExplosion',
    Image: Object.assign(new Image(), { src: '/effect/mediumGreenExplosion.png' }),
    AnimationFrame: 9,
    width: 63.5,
    height: 63.5,
    scalingFactor: 0.9,
  },
  largeExplosion: {
    Kind: 'largeExplosion',
    Image: Object.assign(new Image(), { src: '/effect/largeExplosion.png' }),
    AnimationFrame: 10,
    width: 480,
    height: 480,
    scalingFactor: 0.7,
  },
  shield: {
    Kind: 'shield',
    Image: Object.assign(new Image(), { src: '/effect/shield.png' }),
    AnimationFrame: 11,
    width: 64,
    height: 128,
    scalingFactor: 2,
  },
};
