import { WeaponMetaData } from './weapon';
import { AnimationMetaData } from './effect';

export const EnemyMetaData = {
  kamekaze: {
    Image: Object.assign(new Image(), { src: '/enemy/kamekazi.png' }),
    weapon: WeaponMetaData.empty,
    width: 45,
    height: 45,
    hitSound: '/audio/hitSound/kamekazi.mp3',
    weaponSound: '',
    blastAnimation: AnimationMetaData.mediumYellowExplosion,
    hp: 0,
    bossFactor: 1,
  },
  fighter: {
    Image: Object.assign(new Image(), { src: '/enemy/fighter.png' }),
    weapon: WeaponMetaData.dropbomb,
    width: 55,
    height: 55,
    hitSound: '/audio/hitSound/fighter.mp3',
    weaponSound: '/audio/weapon/dropbomb.mp3',
    blastAnimation: AnimationMetaData.mediumYellowExplosion,
    hp: 0,
    bossFactor: 1,
  },
  chaser: {
    Image: Object.assign(new Image(), { src: '/enemy/chaser.png' }),
    weapon: WeaponMetaData.homing,
    width: 50,
    height: 50,
    hitSound: '/audio/hitSound/chaser.mp3',
    weaponSound: '/audio/weapon/homing.mp3',
    blastAnimation: AnimationMetaData.mediumGreenExplosion,
    hp: 0,
    bossFactor: 1,
  },
  nuker: {
    Image: Object.assign(new Image(), { src: '/enemy/nuker.png' }),
    weapon: WeaponMetaData.nuke,
    width: 55,
    height: 55,
    hitSound: '/audio/hitSound/nuker.mp3',
    weaponSound: '/audio/weapon/nuke.mp3',
    blastAnimation: AnimationMetaData.mediumGreenExplosion,
    hp: 0,
    bossFactor: 0.1,
  },
  crabBoss: {
    Image: Object.assign(new Image(), { src: '/enemy/crabBoss.png' }),
    weapon: WeaponMetaData.nuke,
    width: 100,
    height: 100,
    hitSound: '/audio/hitSound/boss.mp3',
    weaponSound: '/audio/weapon/nuke.mp3',
    blastAnimation: AnimationMetaData.largeExplosion,
    hp: 19,
    bossFactor: 1.5,
  },
  fighterBoss: {
    Image: Object.assign(new Image(), { src: '/enemy/fighterBoss.png' }),
    weapon: WeaponMetaData.invbullet,
    width: 90,
    height: 90,
    hitSound: '/audio/hitSound/boss.mp3',
    weaponSound: '/audio/weapon/invbullet.mp3',
    blastAnimation: AnimationMetaData.largeExplosion,
    hp: 11,
    bossFactor: 1,
  },
  gunShip: {
    Image: Object.assign(new Image(), { src: '/enemy/gunship.png' }),
    weapon: WeaponMetaData.homing,
    width: 150,
    height: 150,
    hitSound: '/audio/hitSound/boss.mp3',
    weaponSound: '/audio/weapon/homing.mp3',
    blastAnimation: AnimationMetaData.largeExplosion,
    hp: 49,
    bossFactor: 20,
  },
};
