export const WeaponMetaData = {
  bullet: {
    Kind: 'bullet',
    Image: Object.assign(new Image(), { src: '/weapon/bullet.png' }),
    AnimationFrame: 3,
    motion: true,
    height: 32,
    width: 32,
    scalingFactor: 1.1,
    fireRate: 100,
  },
  dropbomb: {
    Kind: 'dropbomb',
    Image: Object.assign(new Image(), { src: '/weapon/dropbomb.png' }),
    AnimationFrame: 2,
    motion: true,
    height: 32,
    width: 32,
    scalingFactor: 2.2,
    fireRate: 170,
  },
  homing: {
    Kind: 'homing',
    Image: Object.assign(new Image(), { src: '/weapon/homing.png' }),
    AnimationFrame: 9,
    motion: true,
    height: 32,
    width: 32,
    scalingFactor: 0.8,
    fireRate: 250,
  },
  nuke: {
    Kind: 'nuke',
    Image: Object.assign(new Image(), { src: '/weapon/nuke.png' }),
    AnimationFrame: 11,
    motion: false,
    height: 45,
    width: 12,
    scalingFactor: 1.3,
    fireRate: 50,
  },
  empty: {
    Kind: 'empty',
  },
};
