export const WeaponMetaData = {
  bullet: {
    Kind: 'bullet',
    Image: Object.assign(new Image(), { src: '/weapon/bullet.png' }),
    AnimationFrame: 3,
    motion: true,
    height: 32,
    width: 32,
    scalingFactor: 1.1,
  },
  dropbomb: {
    Kind: 'dropbomb',
    Image: Object.assign(new Image(), { src: '/weapon/dropbomb.png' }),
    AnimationFrame: 2,
    motion: true,
    height: 32,
    width: 32,
    scalingFactor: 2.2,
  },
  homing: {
    Kind: 'homing',
    Image: Object.assign(new Image(), { src: '/weapon/homing.png' }),
    AnimationFrame: 9,
    motion: true,
    height: 32,
    width: 32,
    scalingFactor: 0.9,
  },
  nuke: {
    Kind: 'nuke',
    Image: Object.assign(new Image(), { src: '/weapon/nuke.png' }),
    AnimationFrame: 11,
    motion: false,
    height: 10,
    width: 10,
    scalingFactor: 1,
  },
  empty: {
    Kind: 'empty',
  },
};
